version: '3.5'
services:
    web:
        build:
            context: ./docker/nginx/
        ports:
        - '${APP_PORT}:80'
        - '${APP_PORT_SSL}:443'
        volumes:
        - 'data:/var/www/'
        - type: bind
          source: ./public_html/${PROJECT_FOLDER}
          target: /var/www/html/
          bind:
            propagation: shared
        - './docker/nginx/conf/:/etc/nginx/conf.d/'
        - './docker/nginx/ssl/:/etc/nginx/certs/'
networks:
  default:
    external:
      name: phpbackend
volumes:
  data:
    name: public_html